name: Publish OCR-D Controller
on:
  push:
    branches: [ "master" ]
  schedule:
     - cron: '0 0 * * 0' # run weekly
  workflow_dispatch: # run manually

env:
  REGISTRY_PATH: ghcr.io/slub
  STABLE_VERSION: 2023-02-07 # manually adjusted when tested https://github.com/slub/ocrd_kitodo

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine build args
      run: |
        date -u +"build_date=%Y-%m-%dT%H:%M:%SZ" >> $GITHUB_ENV
        echo "vcs_ref=`git rev-parse --short HEAD`" >> $GITHUB_ENV

    - name: Build the latest OCR-D Controller image and deploy to GitHub Container Repository
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_PATH }}/ocrd_controller:latest
        build-args: |
          BUILD_DATE=${{ env.build_date }}
          VCS_REF=${{ env.vcs_ref }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build the stable OCR-D Controller image and deploy to GitHub Container Repository
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY_PATH }}/ocrd_controller:stable
        build-args: |
          BUILD_DATE=${{ env.build_date }}
          VCS_REF=${{ env.vcs_ref }}
          VERSION=${{ env.STABLE_VERSION }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
