name: Publish OCR-D Controller

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: The branch, tag or SHA to checkout. Otherwise, uses the default branch.
      image-tag:
        description: Tag name of Docker image
        default: 'latest'
      ocrd-all-version: 
        description: Tag of ocrd/all from stage
        default: 'maximum-git'  

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Remove unwanted to provide more disk space
      # https://github.com/marketplace/actions/maximize-build-disk-space
      # https://github.com/actions/runner-images/issues/2840
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
    
    - name: Checkout without input reference (default)
      uses: actions/checkout@v3
      if: github.event.inputs.checkout-ref == ''
    
    - name: Checkout input reference ${{ github.event.inputs.checkout-ref }}
      uses: actions/checkout@v3
      if: github.event.inputs.checkout-ref != ''
      with:
        ref: ${{ github.event.inputs.checkout-ref }}

    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine build args
      run: |
        date -u +"build_date=%Y-%m-%dT%H:%M:%SZ" >> $GITHUB_ENV
        echo "vcs_ref=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        echo "vcs_tag=`git describe --always --tags --abbrev=0 HEAD 2>/dev/null`" >> $GITHUB_ENV

    - name: Build the OCR-D Controller image (ghcr.io/slub/ocrd_controller:${{ github.event.inputs.image-tag }}) and deploy to GitHub Container Repository
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/slub/ocrd_controller:${{ github.event.inputs.image-tag }}
        build-args: |
          BUILD_DATE=${{ env.build_date }}
          VCS_REF=${{ env.vcs_ref }}
          VERSION=${{ github.event.inputs.ocrd-all-version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
