name: Publish OCR-D Controller image

on:
  workflow_dispatch:
    inputs:
      image-tag: 
        default: 'latest'
      ocrd-all-version: 
        default: 'maximum-git'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - # Activate cache export feature to reduce build time of images
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine build args
      run: |
        date -u +"build_date=%Y-%m-%dT%H:%M:%SZ" >> $GITHUB_ENV
        echo "vcs_ref=`git rev-parse --short HEAD`" >> $GITHUB_ENV
        echo "vcs_tag=`git describe --always --tags --abbrev=0 HEAD 2>/dev/null`" >> $GITHUB_ENV

    - name: Build the latest OCR-D Controller image and deploy to GitHub Container Repository
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/slub/ocrd_controller:${{ github.event.inputs.image-tag }}
        build-args: |
          BUILD_DATE=${{ env.build_date }}
          VCS_REF=${{ env.vcs_ref }}
          VERSION=${{ github.event.inputs.ocrd-all-version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
